### ISSUE TITLE
Wrong versionCode in APK of 1.0.1

### ISSUE THREAD

**Issue by IzzySoft** [angelgladin/Photo_EXIF_Toolkit#34]
Just a short note: When releasing v1.0.1, you forgot to increase the versionCode.

    # version 1.0:
    package: name='com.angelgladin.photoexiftoolkit' versionCode='1' versionName='1.0' platformBuildVersionName='7.1.1'
    # version 1.0.1:
    package: name='com.angelgladin.photoexiftoolkit' versionCode='1' versionName='1.0.1' platformBuildVersionName='7.1.1'

That causes issues with updates, as the two will be considered the same. So please remember increasing that number as well for future updates :smile_cat:

**Comment by angelgladin** [comment]
Oh, didn't know that, thanks for the advice. 👍 I will change it the next time I change the versionName.

**Comment by IzzySoft** [comment]
It's especially problematic when hosted in an repo, as there it's considered "duplicate" then. Let me update #16 with a nice little goodie :smiley_cat:

**Comment by angelgladin** [comment]
Great, thanks 🤓

**Comment by IzzySoft** [comment]
You're welcome :innocent:
