### ISSUE TITLE
App still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [angelgladin/Photo_EXIF_Toolkit#36]
With the last release (and commit) almost 2 years ago: do you still maintain this app, @angelgladin? Will there be future updates?

If yes (which I hope): any chance to make it really open source, and get rid of the proprietary libraries used (Firebase, GMS)?

**Comment by IzzySoft** [comment]
@angelgladin any pointer ^^?

**Comment by angelgladin** [comment]
Hi @IzzySoft, unfortunately, the app will no longer be maintained due currently, I'm studying my B.S. degree and I'm completely busy at the moment!
Would be great if you (or any volunteer) take this project and continue it. I'm open to any change.

Sorry!

**Comment by IzzySoft** [comment]
Sad to read that @angelgladin – but of course your priorities are right. I'm no Android dev, so I cannot take over (and even if I were, I'd lack the time)…

Thanks for answering, though – as now at least the status is clear. May I suggest to archive this repo (can be done via its settings here at Github), or place a corresponding note in the Readme? Both can be undone should you find time and decide to continue this project.
